controller_list:
  - name: fake_arm_left_controller
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
  - name: fake_left_hand_controller
    joints:
      - hand_left_index_joint
      - hand_left_mrl_joint
      - hand_left_thumb_joint
  - name: fake_arm_right_controller
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
  - name: fake_right_hand_controller
    joints:
      - hand_right_index_joint
      - hand_right_mrl_joint
      - hand_right_thumb_joint
  - name: fake_torso_controller
    joints:
      - torso_lift_joint
