# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_left_1_joint:
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_2_joint:
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_3_joint:
    has_velocity_limits: true
    max_velocity: 2.35
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_4_joint:
    has_velocity_limits: true
    max_velocity: 2.35
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_5_joint:
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_6_joint:
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_7_joint:
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_1_joint:
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_2_joint:
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_3_joint:
    has_velocity_limits: true
    max_velocity: 2.35
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_4_joint:
    has_velocity_limits: true
    max_velocity: 2.35
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_5_joint:
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_6_joint:
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_7_joint:
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: false
    max_acceleration: 0
  # pal-gripper
  gripper_left_left_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_right_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_left_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_right_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  # schunk-wsg
  gripper_left_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: false
    max_acceleration: 0
  # pal-hey5
  hand_right_index_joint:
    has_velocity_limits: true
    max_velocity: 3.35
    has_acceleration_limits: false
    max_acceleration: 0
  hand_right_mrl_joint:
    has_velocity_limits: true
    max_velocity: 3.56
    has_acceleration_limits: false
    max_acceleration: 0
  hand_right_thumb_joint:
    has_velocity_limits: true
    max_velocity: 3.35
    has_acceleration_limits: false
    max_acceleration: 0
  torso_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.07000000000000001
    has_acceleration_limits: false
    max_acceleration: 0