tiago:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - caster_back_left_1_joint
      - caster_back_left_2_joint
      - caster_back_right_1_joint
      - caster_back_right_2_joint
      - caster_front_left_1_joint
      - caster_front_left_2_joint
      - caster_front_right_1_joint
      - caster_front_right_2_joint
      - suspension_left_joint
      - wheel_left_joint
      - suspension_right_joint
      - wheel_right_joint
      - torso_lift_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
      - hand_left_index_joint
      - hand_left_mrl_joint
      - hand_left_thumb_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      - hand_right_index_joint
      - hand_right_mrl_joint
      - hand_right_thumb_joint
      - head_1_joint
      - head_2_joint
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: left_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - arm_left_1_joint
        - arm_left_2_joint
        - arm_left_3_joint
        - arm_left_4_joint
        - arm_left_5_joint
        - arm_left_6_joint
        - arm_left_7_joint
    - name: left_hand_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - hand_left_index_joint
        - hand_left_mrl_joint
        - hand_left_thumb_joint
    - name: left_arm_torso_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - torso_lift_joint
        - arm_left_1_joint
        - arm_left_2_joint
        - arm_left_3_joint
        - arm_left_4_joint
        - arm_left_5_joint
        - arm_left_6_joint
        - arm_left_7_joint
    - name: right_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - arm_right_1_joint
        - arm_right_2_joint
        - arm_right_3_joint
        - arm_right_4_joint
        - arm_right_5_joint
        - arm_right_6_joint
        - arm_right_7_joint
    - name: right_hand_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - hand_right_index_joint
        - hand_right_mrl_joint
        - hand_right_thumb_joint
    - name: right_arm_torso_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - torso_lift_joint
        - arm_right_1_joint
        - arm_right_2_joint
        - arm_right_3_joint
        - arm_right_4_joint
        - arm_right_5_joint
        - arm_right_6_joint
        - arm_right_7_joint
    - name: torso_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        [torso_lift_joint]
    - name: both_arms_torso_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - torso_lift_joint
        - arm_left_1_joint
        - arm_left_2_joint
        - arm_left_3_joint
        - arm_left_4_joint
        - arm_left_5_joint
        - arm_left_6_joint
        - arm_left_7_joint
        - arm_right_1_joint
        - arm_right_2_joint
        - arm_right_3_joint
        - arm_right_4_joint
        - arm_right_5_joint
        - arm_right_6_joint
        - arm_right_7_joint